name: TestTemplate
description: test a new issue creation template, make redaction easier, etc.
labels: kind/test
body:
  - type: textarea
    id: feature
    attributes:
      label: What should be tested or changed?
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
